#!/usr/bin/env bash

set -euo pipefail

ROOT-RUN apk update
ROOT-RUN apk upgrade
ROOT-RUN apk add sudo bash
ROOT-RUN echo \'%wheel ALL=\(ALL:ALL\) NOPASSWD: ALL\' \> /etc/sudoers.d/wheel
ROOT-RUN setup-user -u -g wheel -k \'$INSTANCE_SSH\' $INSTANCE_USER
ROOT-RUN sed -iEe \"s,/home/$INSTANCE_USER:/bin/sh,/home/$INSTANCE_USER:/bin/bash,\" /etc/passwd
ROOT-RUN sed -iEe \"s,^#*\s*PermitRootLogin.*,PermitRootLogin no,\" /etc/ssh/sshd_config
ROOT-RUN service sshd restart
