#!/usr/bin/env bash

set -euo pipefail

function alpine_add_disk(){
  local volume_name=$VOLUME_NAME
  local volume_mount=$VOLUME_MOUNT
  local dev_name=/dev/${volume_name}
  local part_name=${dev_name}1
  RUN sudo apk add parted xfsprogs lsblk
  RUN sudo parted $dev_name mklabel gpt
  RUN sudo parted $dev_name mkpart primary 0% 100%
  RUN sudo mkfs.xfs $part_name
  RUN sudo mkdir $volume_mount
  RUN sudo mount -t xfs $part_name $volume_mount
  RUN 'echo UUID=$(sudo lsblk -no UUID '$part_name') '$volume_mount' xfs  defaults,nofail  0  2 | sudo tee -a /etc/fstab'
}

alpine_add_disk