services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - ./mysql/etc/conf.d:/etc/mysql/conf.d:ro
      - ./volumes/data/mysql:/var/lib/mysql:Z
      - ./volumes/mass/mysql:/mnt/mass/mysql:Z
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: $INSTANCE_ROOT_PASSWORD
      MARIADB_USER: lorenzo
      MARIADB_PASSWORD: $INSTANCE_ROOT_PASSWORD

  admin:
    container_name: phpmyadmin
    build:
      context: ./phpmyadmin
    restart: always
    volumes:
      - config_mysql:/etc/phpmyadmin/config_mysql:ro
      - ./phpmyadmin/etc/conf.d:/etc/phpmyadmin/conf.d:ro
      - ./volumes/mass/phpmyadmin:/var/www/mass:Z
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  config_mysql:
    name: config_mysql
    driver_opts:
      type: cifs
      o: ro,gid=1000,uid=1000,username=$SHARED_USERNAME,password=$SHARED_PASSWORD
      device: //$SHARED_IP/config/mysql.lone
